### ISSUE TITLE
MacOS Installation Troubles

### ISSUE THREAD

**Issue by fuzzyweapon** [albacoretuna/moro#249]
Mac could use some love.  I first tried installing with npm and got an error ([2019-12-09T09_13_36_632Z-debug.log](https://github.com/albacoretuna/moro/files/3938820/2019-12-09T09_13_36_632Z-debug.log)).

And then when following directions for grabbing the binaries instead?
[moro-binary.log](https://github.com/albacoretuna/moro/files/3938830/moro-binary.log)

I feel like I must be missing something critical for the latter?  Did I overlook some buried documentation?

I didn't enter these as two separate issues because frankly, I don't **think** that the responsibility of the first issue lies with moro and the latter seems more like user error.

**Comment by albacoretuna** [comment]
Hi @fuzzyweapon sorry to hear about your problems. What node and npm versions are you using? I couldn't find it in the logs. 

This should be fixed properly, but as a work around seems like if you create a file in your home directory and name it .moro-config.json and copy these defaults into it, the binary should work for you. 

```
{"BREAK_DEFAULT":30,"HOURS_IN_A_WORK_DAY":7.5,"DATE_FORMAT":"YYYY-MM-DD","DB_FILE_MAIN":""}
```

**Comment by albacoretuna** [comment]
Moro 5 was published today and I tested it on macos + node 12. This issue should be fixed.
